<a href="https://colab.research.google.com/github/excelasaph/Create-a-Neuron/blob/main/Excel_Asaph%26Christain_Iradukunda_Live_coding_Neuron_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Write a class Neuron that defines a single neuron performing binary classification:

class constructor: def __init__(self, nx):
nx is the number of input features to the neuron
If nx is not an integer, raise a TypeError with the exception: nx must be an integer
If nx is less than 1, raise a ValueError with the exception: nx must be a positive integer
All exceptions should be raised in the order listed above
Public instance attributes:
W: The weights vector for the neuron. Upon instantiation, it should be initialized using a random normal distribution.
b: The bias for the neuron. Upon instantiation, it should be initialized to 0.
A: The activated output of the neuron (prediction). Upon instantiation, it should be initialized to 0.

In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv('https://gist.githubusercontent.com/armgilles/194bcff35001e7eb53a2a8b441e8b2c6/raw/92200bc0a673d5ce2110aaad4544ed6c4010f687/pokemon.csv')

data.head(5)


#                   Name Type 1  Type 2  Total  HP  Attack  Defense  \
0  1              Bulbasaur  Grass  Poison    318  45      49       49   
1  2                Ivysaur  Grass  Poison    405  60      62       63   
2  3               Venusaur  Grass  Poison    525  80      82       83   
3  3  VenusaurMega Venusaur  Grass  Poison    625  80     100      123   
4  4             Charmander   Fire     NaN    309  39      52       43   

   Sp. Atk  Sp. Def  Speed  Generation  Legendary  
0       65       65     45           1      False  
1       80       80     60           1      False  
2      100      100     80           1      False  
3      122      120     80           1      False  
4       60       50     65           1      False

In [3]:
#data.info()
new_data = pd.get_dummies(data)
new_data.head(5)

#  Total  HP  Attack  Defense  Sp. Atk  Sp. Def  Speed  Generation  \
0  1    318  45      49       49       65       65     45           1   
1  2    405  60      62       63       80       80     60           1   
2  3    525  80      82       83      100      100     80           1   
3  3    625  80     100      123      122      120     80           1   
4  4    309  39      52       43       60       50     65           1   

   Legendary  ...  Type 2_Ghost  Type 2_Grass  Type 2_Ground  Type 2_Ice  \
0      False  ...         False         False          False       False   
1      False  ...         False         False          False       False   
2      False  ...         False         False          False       False   
3      False  ...         False         False          False       False   
4      False  ...         False         False          False       False   

   Type 2_Normal  Type 2_Poison  Type 2_Psychic  Type 2_Rock  Type 2_Steel  \
0          False           True           False        False         False   
1          False           True           False        False         False   
2          False           True           False        False         False   
3          False           True           False        False         False   
4          False          False           False        False         False   

   Type 2_Water  
0         False  
1         False  
2         False  
3         False  
4         False  

[5 rows x 846 columns]

In [8]:
input = np.array(new_data.drop(['Legendary'], axis = 1), dtype=float)
print(input)

[[  1. 318.  45. ...   0.   0.   0.]
 [  2. 405.  60. ...   0.   0.   0.]
 [  3. 525.  80. ...   0.   0.   0.]
 ...
 [720. 600.  80. ...   0.   0.   0.]
 [720. 680.  80. ...   0.   0.   0.]
 [721. 600.  80. ...   0.   0.   1.]]


In [10]:
print(input.shape)

(800, 845)


In [11]:
nx = input.shape[1]

In [12]:
class Neuron:
  def __init__(self, nx):
    # Validations
    if not isinstance(nx, int):
            raise TypeError("nx must be an integer")
    if nx < 1:
          raise ValueError("nx must be a positive integer")

    # Private variables
    self.W = np.random.normal(size=(1, nx))
    self.b = 0
    self.A = 0.0

  def lin_reg(self, X):
    # Calculate z using linear equation mx = b
    return np.dot(self.W, X) + self.b

  def sigmoid(self, Z):
    # Squeeze the output to be btn 0-1
    return 1 / (1 + np.exp(-Z))

  def forward_propagate(self, X):
    Z = self.lin_reg(X)
    self.A = self.sigmoid(Z)
    return self.A


In [15]:
# Transpose to allow matrix multiplication
X_test = input.T
# Y_test needs to be (1, m)
Y_test = np.array(new_data['Legendary'].astype(int)).reshape(1, X_test.shape[1])

# Get the number of examples
num_examples = X_test.shape[1]

print("--- Data Preparation ---")
print(f"Shape of X_test (features, examples): {X_test.shape}")
print(f"Shape of Y_test (1, examples): {Y_test.shape}")
print(f"Number of features (nx) used for Neuron: {nx}")
print(f"Number of examples (m): {num_examples}")
print("-" * 40)

# 2. Instantiate your Neuron
try:
    print("--- Neuron Instantiation ---")
    my_neuron = Neuron(nx=nx) # nx is already defined from your code
    print("Neuron instantiated successfully!")
    print(f"Neuron's initial Weight (W) shape: {my_neuron.W.shape}")
    print(f"Neuron's initial Bias (b): {my_neuron.b}")
    print(f"Neuron's initial Activation (A): {my_neuron.A}")
    print("-" * 40)

    # 3. Make Predictions
    print("--- Forward Propagation ---")
    # These predictions are probabilities btn 0 - 1
    A_predictions = my_neuron.forward_propagate(X_test)

    print(f"Shape of predictions (A_predictions): {A_predictions.shape}")
    print("First 5 raw predictions: ")
    print(A_predictions[0, :5])
    print("-" * 40)

    # 4. Convert probabilities to binary predictions(0 for False, 1 for True)
    print("--- Binary Predictions & Comparison ---")
    # We use a threshold of 0.5
    binary_preds = (A_predictions >= 0.5).astype(int)
    print("First 5 binary predictions: ")
    print(binary_preds[0, :5])
    print("Actual first 5 Y values:")
    print(Y_test[0, :5])
    print("-" * 40)

    # 5. (Optional) Very basic accuracy check
    print("--- Basic Accuracy (Untrained Neuron) ---")
    accuracy = np.mean(binary_preds == Y_test) * 100
    print(f"Accuracy of the (untrained) neuron: {accuracy:.2f}%")

except TypeError as te:
    print(f"TypeError during testing: {te}")
except ValueError as ve:
    print(f"ValueError during testing: {ve}")
except Exception as e:
    print(f"An unexpected error occurred during testing: {e}")

--- Data Preparation ---
Shape of X_test (features, examples): (845, 800)
Shape of Y_test (1, examples): (1, 800)
Number of features (nx) used for Neuron: 845
Number of examples (m): 800
----------------------------------------
--- Neuron Instantiation ---
Neuron instantiated successfully!
Neuron's initial Weight (W) shape: (1, 845)
Neuron's initial Bias (b): 0
Neuron's initial Activation (A): 0.0
----------------------------------------
--- Forward Propagation ---
Shape of predictions (A_predictions): (1, 800)
First 5 raw predictions: 
[1. 1. 1. 1. 1.]
----------------------------------------
--- Binary Predictions & Comparison ---
First 5 binary predictions: 
[1 1 1 1 1]
Actual first 5 Y values:
[0 0 0 0 0]
----------------------------------------
--- Basic Accuracy (Untrained Neuron) ---
Accuracy of the (untrained) neuron: 8.12%
